"""Module model — maps 1:1 to existing learning path chapters."""
import uuid
from datetime import datetime
from sqlalchemy import String, Integer, DateTime, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base


class Module(Base):
    """A learning module corresponding to one chapter of a learning path.

    Each module contains 3-5 lessons generated by the ModuleOutlineAgent.
    Lesson content is generated on-demand when the learner starts each lesson.
    """

    __tablename__ = "modules"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    path_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("learning_paths.id"), nullable=False
    )
    chapter_number: Mapped[int] = mapped_column(
        Integer, nullable=False
    )
    skill_id: Mapped[str] = mapped_column(String(50), nullable=False)
    skill_name: Mapped[str] = mapped_column(String(255), nullable=False)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    current_level: Mapped[int] = mapped_column(Integer, default=0)
    target_level: Mapped[int] = mapped_column(Integer, default=1)
    lesson_outline: Mapped[dict] = mapped_column(
        JSON, nullable=True
    )  # [{lesson_number, title, type, focus_area, estimated_minutes}]
    total_lessons: Mapped[int] = mapped_column(Integer, default=3)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )

    # Relationships
    learning_path: Mapped["LearningPath"] = relationship(
        "LearningPath", back_populates="modules"
    )
    lessons: Mapped[list["Lesson"]] = relationship(
        "Lesson", back_populates="module", cascade="all, delete-orphan"
    )
